services:
  db_ci_cd:
    image: postgres
    container_name: db_ci_cd
    restart: always
    ports:
      - 2000:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  node:
    container_name: node
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db_ci_cd
volumes:
  postgres: